// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"; // this is needed, if not url: env("DATABASE_URL") is undefined //
			// loads .env into process.env this is important if not process.env would be undefined //
import { defineConfig, env } from "prisma/config"; // define Config : validates and types Prisma Command Line Interface config //
						// env(): safely reads required environment variables //
						// throws a clear error if DATABASE_URL is missing //

export default defineConfig({ // tells Prisma command line interface 
  schema: "prisma/schema.prisma", // where schema lives //
  migrations: {
    path: "prisma/migrations", // where migrations go //
  },
  datasource: {
    url: env("DATABASE_URL"), // how to connect to database //
  },
});

npx prisma migrate dev
npx prisma db push
npx prisma generate 

